export type Item = {
  _id: string;
  activeDay: string;
  category: string;
  dateCreated: string;
  dateSolved: string;
  details: string;
  email: string;
  fullname: string;
  ispaid: boolean;
  major: string;
  meetType: string;
  partname: string;
  partprice: string;
  phonenumber: string;
  problems: string;
  purgable: string;
  review: string;
  servicefee: string;
  status: string;
  timePref: string;
  uniquecode: string;
  username: string;
};
